name: Master Branch

on:
  schedule:
    - cron: 0 0 */3 * *

jobs:
        run-script:
          runs-on: self-hosted
      
          steps:
          - name: Checkout repository
            uses: actions/checkout@v2
      
          - name: Prepare Test Environment
            run: |
              chmod +x ./01_prepare_test_environment.sh
              ./01_prepare_test_environment.sh
      
          - name: Execute Unit Tests
            run: |
              chmod +x ./02_omini_unittests.sh
              ./02_omini_unittests.sh
      
          - name: Start Host Applications
            run: |
              chmod +x ./03_omini_start_host_applications.sh
              ./03_omini_start_host_applications.sh
      
          - name: Execute Integration Tests
            run: |
              chmod +x ./04_omini_integrationtests.sh
              ./04_omini_integrationtests.sh
      
          - name: Stop Host Applications
            if: always()
            run: |
                chmod +x ./98_omini_stop_host_applications.sh
                ./98_omini_stop_host_applications.sh
      
          - name: Tear down tests environment
            run: |
              chmod +x ./99_tear_down_test_environment.sh
              ./99_tear_down_test_environment.sh
      
          - name: Archive Test Artifacts
            if: always()
            uses: actions/upload-artifact@v2
            with:
              name: test-artifacts
              path: ./Omni/tests/integration_tests/Temp